=== AakashPatel008/XML-Schema-and-DTD/XML/Library.dtd
<!DOCTYPE books [
  <!ELEMENT books (book+)>
  <!ELEMENT book (title, author, publisher, year, price)>
  <!ATTLIST book
    id CDATA #REQUIRED>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT author (#PCDATA)>
  <!ELEMENT publisher (#PCDATA)>
  <!ELEMENT year (#PCDATA)>
  <!ELEMENT price (#PCDATA)>
]>

=== AakashPatel008/XML-Schema-and-DTD/XML/Library.XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE note SYSTEM "Library.dtd">
<books xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="Library.xsd">
  <book id="B001">
    <title>2 States</title>
    <author>Cheetan Bhagat</author>
    <publisher>Rupa Publications Pvt. Ltd</publisher>
    <year>2009</year>
    <price>9.99</price>
  </book>
  <book id="B002">
    <title>Spy x Family</title>
    <author>Tatsuya Endo</author>
    <publisher>VIZ Media LLC</publisher>
    <year>2023</year>
    <price>9.99</price>
  </book>
  <book id="B003">
    <title>Naruto, Volume 1</title>
    <author>Masashi Kishimoto</author>
    <publisher>VIZ Media LLC</publisher>
    <year>2003</year>
    <price>12.99</price>
  </book>
  <book id="B004">
    <title>Harry Potter and the Sorcerer's Stone: MinaLima Edition (Harry Potter Series #1)</title>
    <author>J. K. Rowling</author>
    <publisher>Scholastic, Inc.</publisher>
    <year>2020</year>
    <price>15.99</price>
  </book>
</books>
